/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as InstructorDashboardRouteImport } from './routes/instructor.dashboard'
import { Route as InstructorCoursesRouteImport } from './routes/instructor.courses'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as InstructorCoursesIndexRouteImport } from './routes/instructor.courses.index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as StudentQuizQuizIdRouteImport } from './routes/student.quiz.$quizId'
import { Route as InstructorCoursesNewRouteImport } from './routes/instructor.courses.new'
import { Route as InstructorAnalyticsQuizIdRouteImport } from './routes/instructor.analytics.$quizId'
import { Route as StudentLearnCourseIdLessonIdRouteImport } from './routes/student.learn.$courseId.$lessonId'
import { Route as InstructorCoursesIdStudentsRouteImport } from './routes/instructor.courses.$id.students'
import { Route as InstructorCoursesIdQuizzesRouteImport } from './routes/instructor.courses.$id.quizzes'
import { Route as InstructorCoursesIdLessonsRouteImport } from './routes/instructor.courses.$id.lessons'
import { Route as InstructorCoursesIdEditRouteImport } from './routes/instructor.courses.$id.edit'
import { Route as AdminCoursesIdEditRouteImport } from './routes/admin.courses.$id.edit'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCoursesRoute = InstructorCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InstructorRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const InstructorCoursesIndexRoute = InstructorCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorCoursesRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentQuizQuizIdRoute = StudentQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorCoursesNewRoute = InstructorCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InstructorCoursesRoute,
} as any)
const InstructorAnalyticsQuizIdRoute =
  InstructorAnalyticsQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => InstructorAnalyticsRoute,
  } as any)
const StudentLearnCourseIdLessonIdRoute =
  StudentLearnCourseIdLessonIdRouteImport.update({
    id: '/learn/$courseId/$lessonId',
    path: '/learn/$courseId/$lessonId',
    getParentRoute: () => StudentRoute,
  } as any)
const InstructorCoursesIdStudentsRoute =
  InstructorCoursesIdStudentsRouteImport.update({
    id: '/$id/students',
    path: '/$id/students',
    getParentRoute: () => InstructorCoursesRoute,
  } as any)
const InstructorCoursesIdQuizzesRoute =
  InstructorCoursesIdQuizzesRouteImport.update({
    id: '/$id/quizzes',
    path: '/$id/quizzes',
    getParentRoute: () => InstructorCoursesRoute,
  } as any)
const InstructorCoursesIdLessonsRoute =
  InstructorCoursesIdLessonsRouteImport.update({
    id: '/$id/lessons',
    path: '/$id/lessons',
    getParentRoute: () => InstructorCoursesRoute,
  } as any)
const InstructorCoursesIdEditRoute = InstructorCoursesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => InstructorCoursesRoute,
} as any)
const AdminCoursesIdEditRoute = AdminCoursesIdEditRouteImport.update({
  id: '/courses/$id/edit',
  path: '/courses/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRouteWithChildren
  '/instructor/courses': typeof InstructorCoursesRouteWithChildren
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/instructor/analytics/$quizId': typeof InstructorAnalyticsQuizIdRoute
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/instructor/courses/$id/edit': typeof InstructorCoursesIdEditRoute
  '/instructor/courses/$id/lessons': typeof InstructorCoursesIdLessonsRoute
  '/instructor/courses/$id/quizzes': typeof InstructorCoursesIdQuizzesRoute
  '/instructor/courses/$id/students': typeof InstructorCoursesIdStudentsRoute
  '/student/learn/$courseId/$lessonId': typeof StudentLearnCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRouteWithChildren
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/instructor/analytics/$quizId': typeof InstructorAnalyticsQuizIdRoute
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/instructor/courses': typeof InstructorCoursesIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/instructor/courses/$id/edit': typeof InstructorCoursesIdEditRoute
  '/instructor/courses/$id/lessons': typeof InstructorCoursesIdLessonsRoute
  '/instructor/courses/$id/quizzes': typeof InstructorCoursesIdQuizzesRoute
  '/instructor/courses/$id/students': typeof InstructorCoursesIdStudentsRoute
  '/student/learn/$courseId/$lessonId': typeof StudentLearnCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRouteWithChildren
  '/instructor/courses': typeof InstructorCoursesRouteWithChildren
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/instructor/analytics/$quizId': typeof InstructorAnalyticsQuizIdRoute
  '/instructor/courses/new': typeof InstructorCoursesNewRoute
  '/student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/instructor/courses/': typeof InstructorCoursesIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/instructor/courses/$id/edit': typeof InstructorCoursesIdEditRoute
  '/instructor/courses/$id/lessons': typeof InstructorCoursesIdLessonsRoute
  '/instructor/courses/$id/quizzes': typeof InstructorCoursesIdQuizzesRoute
  '/instructor/courses/$id/students': typeof InstructorCoursesIdStudentsRoute
  '/student/learn/$courseId/$lessonId': typeof StudentLearnCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/users'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/instructor/analytics/$quizId'
    | '/instructor/courses/new'
    | '/student/quiz/$quizId'
    | '/admin/courses/'
    | '/instructor/courses/'
    | '/admin/courses/$id/edit'
    | '/instructor/courses/$id/edit'
    | '/instructor/courses/$id/lessons'
    | '/instructor/courses/$id/quizzes'
    | '/instructor/courses/$id/students'
    | '/student/learn/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/users'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/instructor/analytics/$quizId'
    | '/instructor/courses/new'
    | '/student/quiz/$quizId'
    | '/admin/courses'
    | '/instructor/courses'
    | '/admin/courses/$id/edit'
    | '/instructor/courses/$id/edit'
    | '/instructor/courses/$id/lessons'
    | '/instructor/courses/$id/quizzes'
    | '/instructor/courses/$id/students'
    | '/student/learn/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/users'
    | '/courses/$courseId'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/student/profile'
    | '/instructor/analytics/$quizId'
    | '/instructor/courses/new'
    | '/student/quiz/$quizId'
    | '/admin/courses/'
    | '/instructor/courses/'
    | '/admin/courses/$id/edit'
    | '/instructor/courses/$id/edit'
    | '/instructor/courses/$id/lessons'
    | '/instructor/courses/$id/quizzes'
    | '/instructor/courses/$id/students'
    | '/student/learn/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses': {
      id: '/instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/instructor/courses/': {
      id: '/instructor/courses/'
      path: '/'
      fullPath: '/instructor/courses/'
      preLoaderRoute: typeof InstructorCoursesIndexRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/quiz/$quizId': {
      id: '/student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/student/quiz/$quizId'
      preLoaderRoute: typeof StudentQuizQuizIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/courses/new': {
      id: '/instructor/courses/new'
      path: '/new'
      fullPath: '/instructor/courses/new'
      preLoaderRoute: typeof InstructorCoursesNewRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/instructor/analytics/$quizId': {
      id: '/instructor/analytics/$quizId'
      path: '/$quizId'
      fullPath: '/instructor/analytics/$quizId'
      preLoaderRoute: typeof InstructorAnalyticsQuizIdRouteImport
      parentRoute: typeof InstructorAnalyticsRoute
    }
    '/student/learn/$courseId/$lessonId': {
      id: '/student/learn/$courseId/$lessonId'
      path: '/learn/$courseId/$lessonId'
      fullPath: '/student/learn/$courseId/$lessonId'
      preLoaderRoute: typeof StudentLearnCourseIdLessonIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/courses/$id/students': {
      id: '/instructor/courses/$id/students'
      path: '/$id/students'
      fullPath: '/instructor/courses/$id/students'
      preLoaderRoute: typeof InstructorCoursesIdStudentsRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/instructor/courses/$id/quizzes': {
      id: '/instructor/courses/$id/quizzes'
      path: '/$id/quizzes'
      fullPath: '/instructor/courses/$id/quizzes'
      preLoaderRoute: typeof InstructorCoursesIdQuizzesRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/instructor/courses/$id/lessons': {
      id: '/instructor/courses/$id/lessons'
      path: '/$id/lessons'
      fullPath: '/instructor/courses/$id/lessons'
      preLoaderRoute: typeof InstructorCoursesIdLessonsRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/instructor/courses/$id/edit': {
      id: '/instructor/courses/$id/edit'
      path: '/$id/edit'
      fullPath: '/instructor/courses/$id/edit'
      preLoaderRoute: typeof InstructorCoursesIdEditRouteImport
      parentRoute: typeof InstructorCoursesRoute
    }
    '/admin/courses/$id/edit': {
      id: '/admin/courses/$id/edit'
      path: '/courses/$id/edit'
      fullPath: '/admin/courses/$id/edit'
      preLoaderRoute: typeof AdminCoursesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminCoursesIdEditRoute: typeof AdminCoursesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminCoursesIdEditRoute: AdminCoursesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface InstructorAnalyticsRouteChildren {
  InstructorAnalyticsQuizIdRoute: typeof InstructorAnalyticsQuizIdRoute
}

const InstructorAnalyticsRouteChildren: InstructorAnalyticsRouteChildren = {
  InstructorAnalyticsQuizIdRoute: InstructorAnalyticsQuizIdRoute,
}

const InstructorAnalyticsRouteWithChildren =
  InstructorAnalyticsRoute._addFileChildren(InstructorAnalyticsRouteChildren)

interface InstructorCoursesRouteChildren {
  InstructorCoursesNewRoute: typeof InstructorCoursesNewRoute
  InstructorCoursesIndexRoute: typeof InstructorCoursesIndexRoute
  InstructorCoursesIdEditRoute: typeof InstructorCoursesIdEditRoute
  InstructorCoursesIdLessonsRoute: typeof InstructorCoursesIdLessonsRoute
  InstructorCoursesIdQuizzesRoute: typeof InstructorCoursesIdQuizzesRoute
  InstructorCoursesIdStudentsRoute: typeof InstructorCoursesIdStudentsRoute
}

const InstructorCoursesRouteChildren: InstructorCoursesRouteChildren = {
  InstructorCoursesNewRoute: InstructorCoursesNewRoute,
  InstructorCoursesIndexRoute: InstructorCoursesIndexRoute,
  InstructorCoursesIdEditRoute: InstructorCoursesIdEditRoute,
  InstructorCoursesIdLessonsRoute: InstructorCoursesIdLessonsRoute,
  InstructorCoursesIdQuizzesRoute: InstructorCoursesIdQuizzesRoute,
  InstructorCoursesIdStudentsRoute: InstructorCoursesIdStudentsRoute,
}

const InstructorCoursesRouteWithChildren =
  InstructorCoursesRoute._addFileChildren(InstructorCoursesRouteChildren)

interface InstructorRouteChildren {
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRouteWithChildren
  InstructorCoursesRoute: typeof InstructorCoursesRouteWithChildren
  InstructorDashboardRoute: typeof InstructorDashboardRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorAnalyticsRoute: InstructorAnalyticsRouteWithChildren,
  InstructorCoursesRoute: InstructorCoursesRouteWithChildren,
  InstructorDashboardRoute: InstructorDashboardRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizQuizIdRoute: typeof StudentQuizQuizIdRoute
  StudentLearnCourseIdLessonIdRoute: typeof StudentLearnCourseIdLessonIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizQuizIdRoute: StudentQuizQuizIdRoute,
  StudentLearnCourseIdLessonIdRoute: StudentLearnCourseIdLessonIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
